from settings import env

# see static.py for static configs
AWS_ACCESS_KEY_ID = env.str('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = env.str('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = env.str('AWS_STORAGE_BUCKET_NAME')
AWS_DEFAULT_ACL = 'public-read'
AWS_S3_REGION_NAME = env.str('AWS_S3_REGION_NAME', default='eu-central-1')
AWS_S3_SIGNATURE_VERSION = 's3v4'

AWS_MEDIACONVERT_ENDPOINT_URL = env.str('AWS_MEDIACONVERT_ENDPOINT_URL')
AWS_MEDIACONVERT_ROLE = env.str('AWS_MEDIACONVERT_ROLE')
AWS_MEDIACONVERT_SUPPORTED_FORMATS = (
    'WMV', '3G2', '3GP', 'AVI', 'MKV', 'MPG',
    'MPEG', 'MP4', 'MOV', 'MXF', 'WEBM',
)
AWS_S3_MEDIA_PATH = f's3://{AWS_STORAGE_BUCKET_NAME}/{MEDIA_DIR}'
