kind: Service
apiVersion: v1

metadata:
  name: {{.Values.Broker.Service.name}}
  namespace: {{.Release.Namespace}}

spec:
  type: NodePort
  selector:
    app: broker
  ports:
    - port: {{.Values.Broker.Service.port}}
      protocol: TCP