kind: Secret
apiVersion: v1

metadata:
  name: aws-secret
  namespace: {{.Release.Namespace}}

type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{.Values.Services.AWS.ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: {{.Values.Services.AWS.SECRET_ACCESS_KEY}}
  AWS_STORAGE_BUCKET_NAME: {{.Values.Services.AWS.STORAGE_BUCKET_NAME}}
  AWS_MEDIACONVERT_ENDPOINT_URL: {{.Values.Services.AWS.MEDIACONVERT_ENDPOINT_URL}}
  AWS_MEDIACONVERT_ROLE: {{.Values.Services.AWS.MEDIACONVERT_ROLE}}