apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
{{/*  namespace: {{.Release.Namespace}}*/}}
stringData:
  SECRET_KEY: {{.Values.Backend.SecretKey}}
  DATABASE_URL: 'mysql://{{.Values.Database.User}}:{{.Values.Database.Password}}@{{.Values.Database.Service.name}}:{{.Values.Database.Service.port}}/{{.Values.Database.Database}}'
  CELERY_BROKER_URL: 'amqp://{{.Values.Broker.User}}:{{.Values.Broker.Password}}@{{.Values.Broker.Service.name}}:{{.Values.Broker.Port}}'