apiVersion: v1
kind: Secret
metadata:
  name: broker-secret
{{/*  namespace: {{.Release.Namespace}}*/}}
stringData:
  RABBITMQ_DEFAULT_USER: {{.Values.Broker.User}}
  RABBITMQ_DEFAULT_PASS: {{.Values.Broker.Password}}