# Generated by Django 3.1.7 on 2021-03-18 19:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

from utils.storages import EncodedVideosStorage, get_file_upload_path, UploadedVideosStorage, VideoThumbnailsStorage
from utils.validators import FileSizeValidator


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncodedVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container', models.CharField(choices=[('webm', 'webm'), ('mp4', 'mp4')], max_length=4)),
                ('file', models.FileField(blank=True, null=True, storage=EncodedVideosStorage, upload_to='')),
            ],
            options={
                'verbose_name': 'encoded video',
                'verbose_name_plural': 'encoded videos',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file',
                 models.FileField(blank=True, null=True, storage=UploadedVideosStorage, upload_to=get_file_upload_path,
                                  validators=
                                  [django.core.validators.FileExtensionValidator(
                                      allowed_extensions=(
                                          'WMV', '3G2', '3GP', 'AVI', 'MKV', 'MPG', 'MPEG', 'MP4', 'MOV', 'MXF',
                                          'WEBM')
                                  ),
                                      FileSizeValidator(max_size=10485760)])),
                ('remote_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('status', models.CharField(
                    choices=[('created', 'Created'), ('encoding', 'Encoding'), ('succeeded', 'Succeeded'),
                             ('failed', 'Failed')], default='created', max_length=9)),
                ('link', models.URLField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, storage=VideoThumbnailsStorage, upload_to='')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
            },
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.CheckConstraint(
                check=models.Q(('link__isnull', False), ('file__isnull', False), _connector='OR'),
                name='file_or_link_provided'),
        ),
        migrations.AddField(
            model_name='encodedvideo',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encoded_videos',
                                    to='videos.video'),
        ),
        migrations.AlterUniqueTogether(
            name='encodedvideo',
            unique_together={('source', 'container')},
        ),
    ]
