# Generated by Django 3.1.7 on 2021-03-18 19:07

from django.db import migrations


def set_up_periodic_tasks(apps, *args, **kwargs):
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    IntervalSchedule = apps.get_model('django_celery_beat', 'IntervalSchedule')

    PeriodicTask.objects.create(
        name='Update encoding tasks',
        task='apps.videos.tasks.update_encoding_tasks',
        interval=IntervalSchedule.objects.create(
            every=30,
            period='seconds',
        ),
        expire_seconds=60
    )


class Migration(migrations.Migration):
    dependencies = [
        ('videos', '0001_initial'),
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
    ]

    operations = [
        migrations.RunPython(set_up_periodic_tasks),
    ]
